### ISSUE TITLE
Autoscaler - cluster limits: max_cores

### ISSUE THREAD

**Issue by elimrovr** [castai/terraform-provider-castai#352]
Why is [MaxCores](https://github.com/castai/terraform-provider-castai/blame/385fda7ce6ebd0e08060b6dde21770889b1b23c4/castai/resource_autoscaler.go#L279) limited to 1000 ? but gui can go higher?

**Comment by linkas45** [comment]
Hi @elimrovr, thanks for reporting this, we found a bug for UI not following CPU max cores limit. We will fix it soon.

**Comment by jakubsolecki** [comment]
@elimrovr in the end we simply removed upper limits for min/max cpu cores for cluster limits in polices. You can find this issue fixed in the `7.31.1` TF provider.
