### ISSUE TITLE
Computed attribute cannot be set after 0.21.0

### ISSUE THREAD

**Issue by phclark** [castai/terraform-provider-castai#61]
We're seeing the error below in our Terraform applies after updating to provider version 0.21.0. The security groups being passed to the argument were not changed since the previous apply, so I'm guessing this is a bug with the new fix in [PR 59](https://github.com/castai/terraform-provider-castai/pull/59), that or do we need to now use `override_security_groups`?

```
│ Error: Computed attribute cannot be set
│ 
│   with castai_eks_cluster.castai_cluster,
│   on cast_eks.tf line 20, in resource "castai_eks_cluster" "castai_cluster":
│   20:   security_groups = [ (redacted) ]
```

**Comment by aldor007** [comment]
hi @phclark 
`security_groups` field was renamed to `override_security_groups` because previously it was causing troubles with users who didn't want to change SGs. 

So to fix the issue you need to use `override_security_groups`.

 Sorry for inconvenience

**Comment by aldor007** [comment]
Information about this breaking change was added to the release note.
